### PR TITLE
Fix for mRo X2.1

### PR DESCRIPTION
**Pull request by tops4u**

### CODE REVIEW

**Review by dagar — APPROVED** [review]

**Comment by mhkabir** [comment]
Why was this merged? This seems to be incorrect.

**Comment by mhkabir** [comment]
The correct target is `px4fmu-v3_default`.

**Comment by mhkabir** [comment]
mRo X2.1 is this : https://store.mrobotics.io/mRo-X2-1-Rev-2-p/mro-x2.1rv2-mr.htm. 

The one changed in this PR is a standard Pixhawk board.

**Comment by dagar** [comment]
My bad, I was reviewing from my phone. Good catch Kabir.

**Comment by dagar** [comment]
Do we even need to mention the mRo pixhawk separately from the pixhawk 1?

**Comment by mhkabir** [comment]
Not really, I guess.

**Comment by tops4u** [comment]
FMUv3 build will not load on the X-2.1 since it has a different Board identifier. AFAIK FMUv3 is similar to v2 except the Silicon Version? X-2.1 has different IMU HW and slso different Orientation of sensors than FMUv2.

**Comment by tops4u** [comment]
Oh my bad... when I was looking through the Docu I was just looking out for mRo, but indeed this line is for the Standard Pixhawk from mRo. So we should add a line for the X-2.1 Variant. Shall I issue a new PR?

**Comment by LorenzMeier** [comment]
Please do a new PR, yes.

**Pull request merged**
