### PR TITLE
Add new info about bash on windows.

### PR DESCRIPTION
**Pull request by lovettchris**
The PX4 build succeeds using [BashOnWindows](https://github.com/Microsoft/BashOnWindows)

### CODE REVIEW

**Comment by LorenzMeier** [comment]
That's pretty cool. How do you install the env for bash on windows?

**Comment by lovettchris** [comment]
You can download [windows 10 anniversary update](https://www.microsoft.com/en-us/software-download/windows10) then enable the windows feature called "Windows Subsystem for Linux (Beta)" using the "Turn Windows features on or off" dialog available from the "Programs and Features" control panel.  Then simply open a command prompt and type "bash".

**Comment by lovettchris** [comment]
Note there's a few more steps to get openjdk, using webupd8 repo outlined [here](http://stackoverflow.com/questions/32942023/ubuntu-openjdk-8-unable-to-locate-package).  But this doesn't seem to be needed for the build.

**Comment by bkueng** [comment]
rebased & applied

**Pull request closed without merging**
