### PR TITLE
try translated_commit:

### PR DESCRIPTION
**Pull request by FantasyJXF**
Should I add the following code to every file?
```
---
translated_commit: https://github.com/PX4/px4_user_guide/blob/e9d8ee6fc72c9d0111c14edaf7c585c0024382aa/book.json 
---
```

### CODE REVIEW

**Comment by hamishwillee** [comment]
@FantasyJXF No. That is for a specific file book.json (which I apologize, was a bad example to use). I will try to add the metadata as a post process. Do you know the date that you took the copy of the files that you translated?

**Comment by hamishwillee** [comment]
@FantasyJXF It would be good if zh/README.md could be translated as this is the first page people see.

**Comment by hamishwillee** [comment]
@FantasyJXF Unfortunately, yesterday we moved all images from /images to /assets. This means that your images are broken in most cases. 

This can be fixed pretty easily by doing a search and replace for "../../images/" to "../../assets/".

**Comment by hamishwillee** [comment]
@LorenzMeier @bkueng This is a partial Chinese translation of the DevGuide. I modified Langs.md and it builds fine. Spot checked some of the translated files using Google translate and those look good too. Image paths need to be updated and minimally I think that the front page should also be translated before we accept this. Fantasy and other Chinese translators plan to continue translating.

Do you have any particular gating criteria for starting to publish a Chinese version?

**Comment by FantasyJXF** [comment]
@hamishwillee OK, I'll translate the README.md by tomorrow with Beijing Time. And I thought I have update the image links, maybe there are still some problems, I'll fix it soon and continue move my translations to the zh repo.

As for time, I fork your repo on April 18, 2017, and always pull your master branch.

As for translated_commit, still don't know how it works

**Comment by hamishwillee** [comment]
Closing - replaced by #128

**Pull request closed without merging**
