### PR TITLE
Add instructions to spawn vehicles in world for multivehicle simulation

### PR DESCRIPTION
**Pull request by Jaeyoung-Lim**
This PR adds instructions for https://github.com/PX4/Firmware/pull/14764, and also updated information of simulating VTOLs

### CODE REVIEW

**Review by hamishwillee — APPROVED** [review]
Awesome. Merging.

**Comment by hamishwillee** [comment]
Waiting on https://github.com/PX4/Firmware/pull/14764 to merge. @Jaeyoung-Lim I assume this will not be in PX4 v1.11?

**Comment by hamishwillee** [comment]
@Jaeyoung-Lim IS this in PX4 v1.11?

**Comment by Jaeyoung-Lim** [comment]
@hamishwillee I am not sure - How can I check?

**Comment by hamishwillee** [comment]
If I knew that, I wouldn't have asked :-). @mrpollo how can I tell if https://github.com/PX4/Firmware/pull/14764 might be cherry picked into the PX4 v1.11 branch? I suspect not, and that very little is, but can you confirm how I tell.

I ask because I don't want to include this PR in the docs if it is not in the right version.

**Comment by hamishwillee** [comment]
@Jaeyoung-Lim FYI there were changes to the source that made this impossible to deconflict. I copied the changes and merged in https://github.com/PX4/Devguide/commit/f99d036852be82136cb2bca293e2e22efd3a9dd4

Assumption is that this is not PX4v1.11.

Thanks very much!

**Comment by Jaeyoung-Lim** [comment]
Thanks!

**Pull request closed without merging**
