### PR TITLE
updated the Chinese README

### PR DESCRIPTION
**Pull request by FantasyJXF**
Please check it

### CODE REVIEW

**Comment by hamishwillee** [comment]
HI @FantasyJXF 

I will discuss with @bkueng and @LorenzMeier if there are any other gating requirements, but IMO this looks really good. I will add any additional tracking information as a "post process".

Does this PR replace your previous PR #127 ? 

For your information you do not need to submit a new PR for every change. What you could have done is committed changes to your branch, and these would show up in the old PR until the branch was merged. You only need a new PR if the old PR is too broken to add to. Hope that makes sense.

**Comment by FantasyJXF** [comment]
My bad, I didn't think too much, maybe you should close the other PR and this one is more complete since its the leastest one.

Next time I will remember that.

**Comment by hamishwillee** [comment]
So this looks OK - ie that you have committed on top of just one PR rather than opening a separate one (there is a time and a place for multiple separate PRs but usually all "related" changes should go in just one)

There are a couple of different types of ways of merging. The preferred way for merging with master is to use what is called a rebase. What this does is pull in the current master and then re-run all your changes on top of the new master - from a git point of view it looks like you started from the current master. This is better than merging different branches. You might want to look this up.

Regards
Hamish

**Comment by hamishwillee** [comment]
@LorenzMeier Can you confirm there are no gating factors for me to merge the first Chinese translation? @bkueng is OK with this.

**Comment by hamishwillee** [comment]
Closing - superceded by #131

**Pull request closed without merging**
