### PR TITLE
Add alternative wifi dongle for video streaming - TL-WN821N

### PR DESCRIPTION
**Pull request by hamishwillee**
Anecdotally this is better - proposed by @AlexisTM in slack. 

I have just added it as a note because the rest of the tutorial is very specific. @AlexisTM, can you confirm that nothing else had to be changed in the configuration? Looking at this the instructions should actually work for any dongle right?

### CODE REVIEW

**Comment by AlexisTM** [comment]
I will ensure that we can do an AP with it (following the tutorial)

**Comment by AlexisTM** [comment]
Badly, this module does not have AP capability. 

I am using it for the offboard mode.

**Comment by hamishwillee** [comment]
@AlexisTM Thanks. So just to be clear, what you're saying is that this module can't be used for this purpose and I should close the PR?

Presumably you're also saying that you can set up an alternative configuration that can use this module? If so, is it worth adding sections to capture that alternative?

**Comment by AlexisTM** [comment]
Yes, I am sorry of that. 

The module does not have the AP/ad-hoc capability so it does not fit this use-case.

Yet it is a good choice for a multi-vehicle setup in offboard mode.

**Comment by hamishwillee** [comment]
Hi @AlexisTM ,

No need to be sorry - this time didn't work out, but another will.

If you think it is a good idea, perhaps you could add a page or section to https://docs.px4.io/en/telemetry/telemetry_wifi.html - I presume that this is the sort of use case you mean?

Cheers
Hamish

**Comment by AlexisTM** [comment]
Kind of, the WiFi is in my case connected to the Onboard computer, not the Pixhawk.
I'll write a page once I find time :)

**Pull request closed without merging**
