### PR TITLE
Update tuning_the_ecl_ekf.md

### PR DESCRIPTION
**Pull request by elton-choi**
Modify Drag Specific Forces description.
bit position 4 in the EKF2_AID_MASK should be modified to bit position 5

### CODE REVIEW

**Comment by hamishwillee** [comment]
Bit position 5 in the [EKF2_AID_MASK](https://dev.px4.io/en/advanced/parameter_reference.html#EKF2_AID_MASK) is undocumented - so if this is correct we should also [ekf2/ekf2_params.c](https://github.com/PX4/Firmware/blob/master/src/modules/ekf2/ekf2_params.c#L554) and regenerate the parameters. 
@priseborough - thoughts?

**Comment by priseborough** [comment]
This is included in https://github.com/PX4/Firmware/pull/7264

**Comment by hamishwillee** [comment]
Thanks. Then we can merge as soon as that goes in.

**Comment by LorenzMeier** [comment]
Awesome, thanks all!

**Pull request merged**
