### PR TITLE
test

### PR DESCRIPTION
**Pull request by FantasyJXF**
Add a Chinese demo

### CODE REVIEW

**Comment by hamishwillee** [comment]
Hi @FantasyJXF 

This looks like you've just done the first bit of a new translation: "Copying the English tree". Is that correct? Would I be correct in thinking that you're going to add the translations too (before we merge this)?

**Comment by andre-nguyen** [comment]
@hamishwillee Do you need help with translating into certain languages?

**Comment by FantasyJXF** [comment]
@hamishwillee Yeah, I just Copied the English tree. During the next a few days, I'm going to move my translations to the `zh` folder, then you could consider to merge the whole thing.

The `test` is just a test.

**Comment by FantasyJXF** [comment]
@andre-nguyen  Chinese?

**Comment by andre-nguyen** [comment]
I could do French

**Comment by hamishwillee** [comment]
@FantasyJXF You don't need to create a pull request to create a test :-) Should I close this PR?

I've been talking to the team and there is some support for moving docs into folders. However this may not be "your" folder structure :-0. I will have a look at this later today. Probably make the changes next week (early). You may want to hold off moving your docs into place until that is done :-)

**Comment by hamishwillee** [comment]
@andre-nguyen 

> Do you need help with translating into certain languages?
> I can do French

That would be awesome, but you might want to wait until next week before starting while we move some files around. Our policy and initial guidelines are [here](https://github.com/px4/px4_user_guide#translation) - this is for the user guide, but the approach will be the same. It is important to note that as a team we haven't done this before, and certainly not with Gitbook. I expect teething problems ... and if you run into issues or ideas to improve, please let me know.

**Comment by andre-nguyen** [comment]
@hamishwillee It seems like it would be a nightmare to maintain though, how would you go about keeping track of which translations are up to date and all that?

**Comment by hamishwillee** [comment]
> @hamishwillee It seems like it would be a nightmare to maintain though, how would you go about keeping track of which translations are up to date and all that?

OK, so firstly you're right - whatever we do, tracking changes is going to be a pain. The suggestions in the [policy](https://github.com/px4/px4_user_guide#translation) are designed to reduce that pain - these are based on what other successful projects have done.
1. We have a base language (English). What this means is that you only need to track changes in the English version, not all translations.
2. Github has very good change control, so you can certainly find out what changes have occurred since a particular date or changelist. 
3. In the [tracking changes](https://github.com/px4/px4_user_guide#tracking-changes) section I propose one way to make this easier on a per-document basis. In summary, you record the commit of the English file that you last translated like this (in the top of your translation)
```
---
translated_commit: https://github.com/PX4/px4_user_guide/blob/e9d8ee6fc72c9d0111c14edaf7c585c0024382aa/book.json
---
```
If you come along later and open that link you will be able to see if the original file has changed and what has changed since the file was translated. If nothing relevant has changed you can update your changeslist to the latest version.

That is a bit painful now, but in future I hope to add some tooling that will automatically parse the data and tell you if any of the original docs/changelists have changed.

**Comment by FantasyJXF** [comment]
@hamishwillee I get it, it's not the right time for me to move my translatons, since the file structures might change any time. You guys might be very busy these days, sorry for that.

Please let me know if you think it's time for me to do sth. 

Thanks.

You can close this PR, I just figured out the PR indicates "Pull Request" 

-_-

**Comment by hamishwillee** [comment]
Hi @FantasyJXF 

I hope to have the new structure ready early next week. I'm still playing with the organisation, but it currently looks like this: https://github.com/hamishwillee/Devguide/tree/hgw_organise_docs_folders/en

I will let you know when this is in :-) Thanks for your patience.

> You can close this PR, I just figured out the PR indicates "Pull Request"

Done!

Regards
Hamish

**Pull request closed without merging**
