### PR TITLE
Make ubuntu_sim_nuttx.sh non-interactive

### PR DESCRIPTION
**Pull request by ShikherVerma**
The `ubuntu_sim_nuttx.sh` script is non-interactive in most places. This PR makes the remaining apt commands non-interactive.

### CODE REVIEW

**Comment by ShikherVerma** [comment]
First of all. Thanks for this script :+1: saved me a lot of time.
However, I was expecting to run it once and let it execute in the background.
But the script stopped at some points due to missing `--yes` for `apt` commands.
Also a few times `sudo` timed out, due to which I had to regularly check if the script is still executing.
This PR only address the `apt` commands.
For fixing `sudo` timeout issue, [this one liner](https://serverfault.com/a/833888) can be added at the start of the script.
Should I add the sudo timeout fix too in this PR?

**Comment by hamishwillee** [comment]
@ShikherVerma Thanks - great to see the script getting a workout from real users. You are quite right that it should be fully non-interactive ... unfortunately I am not a bash expert, so I missed these cases in my testing.

1. Could you also apply this change to the other scripts in the same directory?

FYI, there is a plan/hope that we will start using at least some of these scripts in our docker provisioning. This will allow us to better test them and keep them maintained ongoing.

2. 
> For fixing sudo timeout issue, this [one liner](https://serverfault.com/a/833888) can be added at the start of the script.
Should I add the sudo timeout fix too in this PR?

@dagar 
- Can you assess the proposed one liner change above?
- Any progress on the thinking to get these scripts used by our docker setup?

**Comment by ShikherVerma** [comment]
> Could you also apply this change to the other scripts in the same directory?

Yeah sure

> FYI, there is a plan/hope that we will start using at least some of these scripts in our docker provisioning. This will allow us to better test them and keep them maintained ongoing.

That would be nice.

**Review by dagar — APPROVED** [review]

**Comment by dagar** [comment]
Looks good to me.

What do you think about moving the scripts to the Firmware repo?

For docker we simply have this part download and execute the script. https://github.com/PX4/containers/blob/master/docker/px4-dev/Dockerfile_base#L11
It may need some tweaks.

**Comment by hamishwillee** [comment]
@ShikherVerma Please make the updates to the other script then we can merge.

@dagar 

> What do you think about moving the scripts to the Firmware repo?

That would be best.

> For docker we simply have this part download and execute the script. https://github.com/PX4/containers/blob/master/docker/px4-dev/Dockerfile_base#L11
It may need some tweaks.

Great. As long as it still works stand-alone for end users I'll be happy. We should perhaps add notes at the top to make it clear that this is used in both docker and in "ordinary" installation?

**Comment by hamishwillee** [comment]
Merged (finally!). Thanks for this.

**Pull request merged**
