### PR TITLE
Add XTDrone Link into ROS and Computer Vsion Pages

### PR DESCRIPTION
**Pull request by bys1123**

### CODE REVIEW

**Comment by hamishwillee** [comment]
Thanks very much. I did a minor post-merge subedit.

**Comment by bys1123** [comment]
Fantastic, Thanks.

**Comment by robin-shaun** [comment]
> Thanks very much. I did a minor post-merge subedit.

Thanks a lot for recommending XTDrone. I'm the author of XTDrone. XTDrone now supports master branch (v1.11), and could you modify 

## External Resources

- [XTDrone](https://github.com/robin-shaun/XTDrone/blob/master/README.en.md) - ROS + PX4 v1.9 simulation environment for computer vision. You could read the [tutorial here](https://www.yuque.com/xtdrone/manual_en) to get started with it.

to

## External Resources

- [XTDrone](https://github.com/robin-shaun/XTDrone/blob/master/README.en.md) - ROS + PX4 simulation platform for computer vision. You could read the [tutorial here](https://www.yuque.com/xtdrone/manual_en) to get started with it.

**Comment by hamishwillee** [comment]
HI @robin-shaun 
I've done it. FYI, your welcome to make these changes yourself : https://dev.px4.io/master/en/contribute/docs.html#quick-changes

**Comment by robin-shaun** [comment]
> HI @robin-shaun
> I've done it. FYI, your welcome to make these changes yourself : https://dev.px4.io/master/en/contribute/docs.html#quick-changes

OK, I have pulled requests.

**Comment by hamishwillee** [comment]
No, I fixed it :-)

**Pull request merged**
