### PR TITLE
Add Snapdragon setup and add RF, RC and ESC wiring instructions

### PR DESCRIPTION
**Pull request by ChristophTobler**

### CODE REVIEW

**Comment by mhkabir** [comment]
:)

**Comment by mhkabir** [comment]
Can we maybe get a nicer airframe picture? This looks really wild. Some zipties would probably help.

**Comment by r0gelion** [comment]
@mhkabir these are the pictures taken from our build, it uses Qualcomm ESC, feel free to use them.
img_20170404_100409
img_20170404_100342
img_20170404_092002

**Comment by r0gelion** [comment]
my bad, the pictures I sent won't match with the description of the build in the page.

**Comment by mhkabir** [comment]
@d3z0rian Many thanks, we may be able to add it later when the Qualcomm ESCs are supported in mainline.

**Pull request merged**
