### PR TITLE
Korean translation

### PR DESCRIPTION
**Pull request by KimEJ**
Translation list
- kr/advanced/parameeter_reference.md
- kr/hardware/REDME.md
- kr/tutorials/linux_sbus.md

### CODE REVIEW

**Comment by hamishwillee** [comment]
@KimEJ The parameter_reference.md is automatically generated from source because the parameters change regularly. There is no way currently for me to store translations in source.

So I am not sure of the best thing for Korean users. If we keep this translation they will have useful text, but it will often be out of date. Also any links from documentation will work, but you won't get any hints that parameters have been removed (as we do for the English version because links break when the parameters are removed).

Alternatively we can just keep the English version that is always up to date. 

What do you think is better for users - translated descriptions or accurate parameter set?

**Comment by hamishwillee** [comment]
PS We could also have a separate document parameter_reference_translated.md for your translation so that the translations are at least available.

**Comment by KimEJ** [comment]
If they were able to read English, they would read the English version with the latest

So I think it would be better than not being translated.

Or I can write note that it is not latest version

**Comment by jeyong** [comment]
The parameter_reference.md is automatically generated from source code. I
think it's just part of source code actually. So it's not necessary to
translate. From my experience in management view. Docs have been changed
quickly, auto-generated pages are easier to be deprecated.

**Comment by hamishwillee** [comment]
Yes, it is hard to manage. In Feb I will try and look at tools to make this easier: https://github.com/PX4/Devguide/issues/419

@KimEJ In the meantime, if the translation is useful we should keep it. Perhaps rename the translation to parameters_korean.md and put this in the tree above the English version of parameters.md. In the translated version you should add a note at the top that states that the translation may be out of date, but that the original English version is [LINK to Enlglish version.] ... does that make sense?

**Comment by KimEJ** [comment]
Roger, but right now is difficult. I'll fix it slowly and pull it.

**Comment by hamishwillee** [comment]
Thanks @KimEJ . For now can you make sure that there is both a translated parameters_translated.md file and the original parameters file in the PR?
Also, please let me know when you're ready for this to be reviewed prior to merging.

**Comment by mrpollo** [comment]
@hamishwillee whats pending in this PR, perhaps we can take it to the finish line if @KimEJ is no longer available

**Comment by KimEJ** [comment]
@mrpollo My company is working on a new project, so it is difficult to fix it right now. So please wait a moment.

It is sorry that I need eating before fix. ㅠㅠ

**Comment by mrpollo** [comment]
Dear @KimEJ, I want to make sure we are doing everything possible to support you in contributing the Korean translation, we understand that you are donating your time and I want to make sure we are giving you the attention you deserve, and if perhaps you no longer have time to work on this because you have other priorities we could assign someone to help. We can for sure wait for you to have free time to help us, we'll be on standby, let us know if you need our help.

**Comment by hamishwillee** [comment]
Hi @KimEJ 

As suggested by @mrpollo I have imported your changes. I have then modified them in https://github.com/PX4/Devguide/pull/441 to add both English and Korean parameters. The Korean version has an *English* note that the parameters may get out of date. 

Thank you for your work here - it is much appreciated! I hope you have time to help us again in future :-)

Regards
Hamish

**Pull request merged**
