### PR TITLE
Multi Vehicle Simulation (SITL) Documentation

### PR DESCRIPTION
**Pull request by mzahana**
This is a documentation of how to setup multi-vehicle simulation, SITL , in Gazebo.

### CODE REVIEW

**Review by LorenzMeier — APPROVED** [review]
Awesome, thanks!

**Comment by DonLakeFlyer** [comment]
No muti-vehicle support in jmavsim SITL? I can never get Gazebo to run.

**Comment by mhkabir** [comment]
@DonLakeFlyer Unfortunately not. What issues are you having with Gazebo? What OS?

**Comment by dogmaphobic** [comment]
macOS Sierra.

```
~$ brew install gazebo7
==> Installing gazebo7 from px4/simulation
Error: px4/simulation/gazebo7 contains conflicting version recursive dependencies:
  boost, boost@1.55
View these with `brew deps --tree px4/simulation/gazebo7`.
```

**Comment by DonLakeFlyer** [comment]
OSX. I either get all sorts of conflicting library problems or if I disregard it just hangs at boot.

**Comment by mhkabir** [comment]
That's odd. If you follow https://github.com/osrf/homebrew-simulation/pull/198 on a clean setup, it should work normally. It worked for me on two different Sierra computers.

@LorenzMeier Any ideas on @dogmaphobic's errors?

**Comment by DonLakeFlyer** [comment]
The most likely problem for me is that by the time you are trying to run both PX4 and ArduPilot SITL they start to stomp on each other with differing but similar dependency requirements.

**Comment by mhkabir** [comment]
OK found the breaking commit : https://github.com/osrf/homebrew-simulation/pull/198/commits/6b1e8df6b53a9829daf37a752cc7b18bf49cb879. 

It worked for me on commit https://github.com/osrf/homebrew-simulation/pull/198/commits/8fa14771d74fcb11bedfb1f5de9c01956be0275f.

**Pull request merged**
