### PR TITLE
Installs PYYAML 3.13 instead of 5.1

### PR DESCRIPTION
**Pull request by ghost**
In PYYAML 5.1 yaml.load is deprecated and add FullLoader and UnsafeLoader classes. The script ubuntu_sim_common_deps.sh throws an error on that.

### CODE REVIEW

**Comment by hamishwillee** [comment]
@dagar This forces a specific lower version of Pyaml. We don't do this in the tested setup script: https://github.com/PX4/Firmware/blob/master/Tools/setup/requirements.txt#L11

1. Do we need to?
2. My understanding is that this script is tested for builds regularly. Is that the case? If this is an error, how did it get through the tests.

**Comment by ghost** [comment]
I am getting this error when launching the SITL simulation.

yaml_error

Installing PYYAML==3.13 solves the issue.

**Comment by mrivi** [comment]
@telegek @hamishwillee That's a MAVROS problem. It's fixed on master and it will be available in the next realese 0.32.0

**Comment by ghost** [comment]
> @telegek @hamishwillee That's a MAVROS problem. It's fixed on master and it will be available in the next release 0.32.0

Great, thanks.

**Comment by hamishwillee** [comment]
Thanks Martina!

**Pull request closed without merging**
