### PR TITLE
Added link to the example ported to python

### PR DESCRIPTION
**Pull request by nkhedekar**
This request is to add a link to the python version of the offboard example (webpage : https://dev.px4.io/en/ros/mavros_offboard.html) 

The main purpose is to provide python developers an example to help them start working with PX4, Gazebo and ROS

### CODE REVIEW

**Comment by hamishwillee** [comment]
Thanks @nkhedekar - excellent.

@TSC21 Generally speaking I'm not a fan of links to "unofficial" github repos. IMO it would be better to either have both examples existing in a repo somewhere where they can easily be tested and kept in sync. Does the [original version](https://dev.px4.io/en/ros/mavros_offboard.html) exist in a repo anywhere? 

If not, should we do so. Either way, might be good to minimally include the Python script inline in this page as well.

Thoughts?

**Comment by lamping7** [comment]
@hamishwillee Offboard examples can be seen in the CI test python source files. https://github.com/PX4/Firmware/tree/master/integrationtests/python_src/px4_it/mavros

There is some bloat due to the rostest framework, but it should serve as a good working example.

**Comment by hamishwillee** [comment]
Thanks @lamping7. @nkhedekar Do you think perhaps instead linking to https://github.com/PX4/Firmware/tree/master/integrationtests/python_src/px4_it/mavros would achieve what you want for this section?

**Comment by nkhedekar** [comment]
Thank you @hamishwillee  and @lamping7.

@hamishwillee yes, I think adding this link (https://github.com/PX4/Firmware/tree/master/integrationtests/python_src/px4_it/mavros) would serve as a good starting point for python developers as it has multiple examples and is properly commented.

**Comment by lamping7** [comment]
These should probably be documented in the CI section of the guide and linked to. But, what is preventing this work, at least for me, are the unknowns about the eventual migration away from the ROS test framework, hinted at here: https://github.com/PX4/Devguide/issues/463 (i.e. I'm not going to spend time writing this if it's going to be tossed out.).

**Comment by hamishwillee** [comment]
@nkhedekar Thanks. I have created https://github.com/PX4/Devguide/pull/490 for the links to integration test code. Will close this now.

**Comment by hamishwillee** [comment]
> These should probably be documented in the CI section of the guide and linked to. But, what is preventing this work, at least for me, are the unknowns about the eventual migration away from the ROS test framework, hinted at here: #463 (i.e. I'm not going to spend time writing this if it's going to be tossed out.).

@lamping7 The plan in #463 is to use DroneCore for most testing, because it is far more lightweight than ROS and puts us much closer to PX4 when testing PX4 functionality.

I think it is worth documenting all the tests to some minimal level even if they might disappear in future. Though I guess it is worth waiting on https://github.com/PX4/Firmware/pull/8915 so that a "pattern is established.

That said, best

**Pull request closed without merging**
