### PR TITLE
setup: remove 404 link, reference to Dockerfile

### PR DESCRIPTION
**Pull request by julianoes**
This link was no longer valid, the Dockerfile is more helpful.

### CODE REVIEW

**Comment by julianoes** [comment]
Also see: https://github.com/PX4/containers/issues/195 and #798.

**Review by hamishwillee — APPROVED** [review]

**Comment by hamishwillee** [comment]
Thanks very much @julianoes  - merging.

Should we remove all the "manual instructions" too? (except the group permissions, which you can't infer from docker)

**Comment by julianoes** [comment]
> Should we remove all the "manual instructions" too? 

I want to follow up with Arch Linux, I'll do it then.

**Comment by hamishwillee** [comment]
Thanks. Sounds excellent. 

What I'd quite like is install scripts that are self documenting, and run in CI - ie run to setup dev environment AND that builds are done for those environments. Then we could reduce the manual setup instructions to just what can't be automated.

**Comment by julianoes** [comment]
Yes, exactly!

**Pull request merged**
