### PR TITLE
Remove fakegps

### PR DESCRIPTION
**Pull request by hamishwillee**
As discussed in https://github.com/PX4/Devguide/pull/345#issuecomment-344528298

### CODE REVIEW

**Comment by TSC21** [comment]
IMO this could be changed instead of deleted, as `fake_gps` is still a possiblility with MAVROS, though the name changed from `mocap_fake_gps.cpp` to `fake_gps.cpp` as it allows other sources of estimated pose besides motion capture

**Comment by hamishwillee** [comment]
@TSC21  So the document (before deleted) said "don't bother with me" see https://dev.px4.io/en/ros/external_position_estimation.html

Happy for it to be recovered - if you think it is useful and can do the work ... or point to someone who knows enough to do so?

**Comment by TSC21** [comment]
We can do some adaptations to https://dev.px4.io/en/ros/external_position_estimation.html to include this. I can do it, though other people are able. @julianoes was the first to write the plugin so he is able to if he has the bandwidth.

**Comment by hamishwillee** [comment]
Thanks. I've added https://github.com/PX4/Devguide/issues/351 to track this. Initially assigned to Julian, though he may ping it back to you!

**Pull request merged**
