### PR TITLE
Updates to support collapsible menu

### PR DESCRIPTION
**Pull request by hamishwillee**
HI @bkueng 

The flat structure of the DevGuide started to annoy me. This update makes the menu collapsible, and does some other minor tweaks. It can be previewed here: https://hamishwillee.gitbooks.io/havdevguide/content/v/collapsible_menu/en/

ANyway, I think this is good. It is now immediately obvious that perhaps AutoPilot Hardware should move somewhere (maybe a concept?) and that the robotics topics might reasonably live under a parent grouping etc.

Let me know what you think.

### CODE REVIEW

**Comment by bkueng** [comment]
Looks definitely better!
Some thoughts & ideas:
- Yes Autopilot Hardware could move to concepts (although it does not quite fit in there either, but I don't have a better place)
- Middleware and Architecture: maybe rename to 'Communication and Architecture', add the ROS and Dronekit topics (and a section for DroneCore?) and move the 'Modules & Commands Reference' to a top-level item (to make it more visible).
- the 'PWM/GPIO Bus' under Sensor and actuator Buses is empty. Should we remove it?
- 'Software Update' only contains a page for the bootloader, which could go under advanced topics
- 'Testing and CI' contains an empty title 'Testing in the Cloud / CI'. Should we remove that?

**Comment by hamishwillee** [comment]
@bkueng 

First thoughts:
> - Yes Autopilot Hardware could move to concepts (although it does not quite fit in there either, but I don't have a better place)

Maybe group all things related to hardware together - so airframes section, companion computers, other related stuff?

> - Middleware and Architecture: maybe rename to 'Communication and Architecture', 

I'm OK with that, but was thinking of grouping ROS etc under "Robotics APIs". 

> move the 'Modules & Commands Reference' to a top-level item (to make it more visible).

Definitely

> - the 'PWM/GPIO Bus' under Sensor and actuator Buses is empty. Should we remove it?

Maybe. Is there anything useful that *should* be in a topic with this name? I'd be tempted to bullet point out content we want and ask for community help to update.

> - 'Software Update' only contains a page for the bootloader, which could go under advanced topics

I think so. I know I say below that I want to split out advanced topics, but only if they have meaningful groupings.

> - 'Testing and CI' contains an empty title 'Testing in the Cloud / CI'. Should we remove that?

Now, we should ask @dagar what is supposed to be there - Daniel?

----

What I would like to do is look at the [tutorials](https://hamishwillee.gitbooks.io/havdevguide/content/v/collapsible_menu/en/tutorials/tutorials.html ) and [advanced topics](https://hamishwillee.gitbooks.io/havdevguide/content/v/collapsible_menu/en/tutorials/tutorials.html) and put the topics in meaningful places for people trying to find out more. So for example group just the debugging topics, move  [Sbus driver](https://hamishwillee.gitbooks.io/havdevguide/content/v/collapsible_menu/en/tutorials/linux_sbus.html) into something about SBUS or drivers or whatever. I'm sure you can see where I am going.

**Comment by bkueng** [comment]
> Maybe group all things related to hardware together - so airframes section, companion computers, other related stuff?

Makes sense.

> I'm OK with that, but was thinking of grouping ROS etc under "Robotics APIs".

That works too.

> Is there anything useful that should be in a topic with this name? I'd be tempted to bullet point out content we want and ask for community help to update.

Hmm, we have some input drivers (e.g. Lidar-Lite) and output drivers (e.g. camera trigger) using PWM, but I don't know enough that I could provide proper documentation.

Splitting the advanced topics and tutorials sounds good to me, especially the advanced section is quite large.

**Comment by dagar** [comment]
>   > 'Testing and CI' contains an empty title 'Testing in the Cloud / CI'. Should we remove that?

> Now, we should ask @dagar what is supposed to be there - Daniel?

I'd say remove it for now. Once we consolidate to a single ci system we could talk about what needs to be documented. I'm hoping a large part of it becomes self explanatory once it's all in the same place.

EDIT: (HAMISH). Done :-)

**Comment by hamishwillee** [comment]
@bkueng OK, so I have:
- removed the empty "Testing in the cloud" heading
- moved one topic "Integration test" from tutorials into test section. It either belongs there or it should be deleted. 
- Split topics into "Debugging/Logging" and "Advanced". 
- Moved the Bootloader topic into "Advanced"
- Deleted "PWM/GPIO Bus" as discussed.
- Moved "Modules & Commands Reference'" to top level. 

I propose we delete this topic: https://hamishwillee.gitbooks.io/havdevguide/content/v/collapsible_menu/en/advanced/fake_gps.html

**The rest requires more thinking. I'd like to merge this as-is and make the other changes as a post-process. OK?**

(further discussion starting in #347)

**Comment by bkueng** [comment]
> I propose we delete this topic: https://hamishwillee.gitbooks.io/havdevguide/content/v/collapsible_menu/en/advanced/fake_gps.html

Agreed

**Pull request merged**
