### PR TITLE
propose to add PlotJuggler

### PR DESCRIPTION
**Pull request by facontidavide**
Hi, 

I added a plugin to my application to load data from ULog. It is somehow experimental but adding it to this list give me the opportunity to get more users and fix more bugs.

Cheers

Davide

### CODE REVIEW

**Comment by TSC21** [comment]
@facontidavide really cool! I usually use PJ with ROS and find it very powerful. Any docs on how to use it as well with uLog are welcomed.

**Comment by facontidavide** [comment]
Simply open the file... then visualize data :)

image

**Comment by TSC21** [comment]
Ahah sounds good!

**Comment by bkueng** [comment]
Nice! We can also add it here: https://docs.px4.io/en/log/flight_log_analysis.html.

**Comment by facontidavide** [comment]
That would be great. Do you need anything from me? A snapshot?

**Comment by hamishwillee** [comment]
Thanks @facontidavide - merged.

> That would be great. Do you need anything from me? A snapshot?

A snapshot showing uLog plots and a short feature list would be great you can see the pattern in https://docs.px4.io/en/log/flight_log_analysis.html

**Comment by MaEtUgR** [comment]
I opened a follow-up issue, see https://github.com/PX4/Devguide/issues/747#issuecomment-465918821

**Pull request merged**
