### PR TITLE
Update uavcan-node-firmware.md

### PR DESCRIPTION
**Pull request by FantasyJXF**
wrong super url

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Thanks!

**Comment by FantasyJXF** [comment]
I send an Email to you, about the Chinese Version Devguide

The website is https://px4.osdrone.net/

I sincerely hope you could have a look at it .

It wont't be better if you could merge it to your homepage.

**Comment by hamishwillee** [comment]
@FantasyJXF @LorenzMeier That looks cool. We can certainly talk about merging. Can you please CC me into your email to @LorenzMeier .

**Comment by FantasyJXF** [comment]
Could you please give me your email?

**Comment by hamishwillee** [comment]
hamishwillee at gmail dot com :-) Sorry about that!

**Comment by FantasyJXF** [comment]
Please check your mailbox

**Pull request merged**
