### PR TITLE
Add def of message_logging_tagged_s

### PR DESCRIPTION
**Pull request by devbharat**
Refer to https://github.com/PX4/pyulog/pull/43 and https://github.com/PX4/Firmware/pull/12144

### CODE REVIEW

**Review by bkueng — COMMENTED** [review]
Can you add the `tag`s that you use, so it's well-defined?
I suggest to start with `0: not specified`, `1: autopilot general`, ...

**Comment by devbharat** [comment]
> Can you add the tags that you use, so it's well-defined?

Might not be very relevant to others. They are names of different processes(handling different system components like different cameras, PPK, Pixracer, Disk etc) that generate those log strings. I could add suggestions as an example.

**Comment by bkueng** [comment]
Yes please add them. It increases the chance that we get consistent tooling.

**Comment by hamishwillee** [comment]
@bkueng FYI This one ready for your re-review.

**Review by bkueng — APPROVED** [review]
Thanks

**Comment by bkueng** [comment]
Can you rebase? Looks like there are conflicts.

**Comment by hamishwillee** [comment]
Thanks. Sorry for late merge!

**Pull request merged**
