### PR TITLE
Snapdragon pinout link

### PR DESCRIPTION
**Pull request by hamishwillee**
Added link to Qualcomm snapdragon pinout info, as suggested by @d3z0rian

### CODE REVIEW

**Comment by hamishwillee** [comment]
@ChristophTobler - you might want to check you're happy with this given your recent submission :-)

**Comment by ChristophTobler** [comment]
@hamishwillee Cool, thanks :+1:

**Comment by LorenzMeier** [comment]
@ChristophTobler Can you review and merge? Thanks!

**Comment by ChristophTobler** [comment]
Commit https://github.com/PX4/Devguide/pull/111/commits/ac712e11e066811f9a97a13688801fdd213343b7 is in master now

**Pull request closed without merging**
