### PR TITLE
simulation-gazebo: switch to version 7

### PR DESCRIPTION
**Pull request by julianoes**
Taken from https://github.com/PX4/PX4Devguide/pull/167.

This works for me for Ubuntu 16.04.
Can somebody please cross test if Gazebo 7 works for Mac OS.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
I'm just installing gazebo7 on Mac. Its a build from source which is sort of annoying.

**Comment by LorenzMeier** [comment]
I did build it, some protobuf related build failures. Will report back.

**Comment by jgoppert** [comment]
I can confirm gazebo-7 + ubuntu 16.04  works. The protobuf version has to be > 2.5 and < 3.0.

**Comment by LorenzMeier** [comment]
Yep, also works on 16.04 with Gazebo 7 and ROS Kinetic here.

**Comment by LorenzMeier** [comment]
And fixed Mac OS.

**Comment by LorenzMeier** [comment]
Rebased and applied.

**Pull request closed without merging**
