### PR TITLE
Update offboard_control.md

### PR DESCRIPTION
**Pull request by fabrizioschiano**
The link to the Odroid XU4 was broken

### CODE REVIEW

**Review by TSC21 — CHANGES_REQUESTED** [review]
I really doubt this link will be permanent. What abou https://magazine.odroid.com/odroid-xu4?

**Comment by fabrizioschiano** [comment]
I also think that the link I proposed will not be permanent. However, it is the closest to the previous link. The one proposed by @TSC21 could be ok too.

**Comment by TSC21** [comment]
> I also think that the link I proposed will not be permanent. However, it is the closest to the previous link. The one proposed by @TSC21 could be ok too.

Can you please update the commit with that link then? Thanks

**Comment by TSC21** [comment]
Thanks!

**Review by TSC21 — APPROVED** [review]

**Pull request merged**
