### PR TITLE
Contributing docs: added pip3 package troubleshoot

### PR DESCRIPTION
**Pull request by Ayshine**
Added troubleshoot section for the error according to Python packages while installing on macOS.

### CODE REVIEW

**Comment by hamishwillee** [comment]
Thanks very much @Ayshine ! I have subedited, removing the "macos" dependency. This could happen on any system.

@julianoes Are you OK with this?

**Comment by Ayshine** [comment]
Thank you @hamishwillee! I hope this test helped somehow. I'm not sure if change with this PR still needed after @julianoes' updates earlier today.

**Comment by hamishwillee** [comment]
@Ayshine It did. Let's see what Julian says. My feeling is that this is generically useful.

**Review by julianoes — APPROVED** [review]
Thanks @Ayshine

**Pull request merged**
