### PR TITLE
Document SWD/JTag Interface mk 2

### PR DESCRIPTION
**Pull request by hamishwillee**
This is second attempt at documenting the SWD interface. I've followed the model of the System Console and just documented SWD rather than trying to cover both at once (e.g. from a "debug port" perspective).

The bulk of the information about specific debug ports has been pushed down to the autopilots. What this does is link to that, and also provide information about the standard debug ports and how to connect some of the more common probes. I think this can probably extend OK as needed.

@davids5 You can see a [rendered view of this here](https://hamishwillee.gitbooks.io/havdevguide/content/v/swd_2/en/debug/swd_debug.html).

Appreciate your review/suggestions. In particular, good to check I put the pin numbers at the right end of the cables :-0

Note, following this there would be some cross linking from other docs TO here.

### CODE REVIEW

**Comment by davids5** [comment]
@hamishwillee - Please click  through the rendered view links you have the wrong links to the GH conectors.  `JST BM06B (6-pin JST GH)` SR are SH family GH have the tab.

**Comment by davids5** [comment]
@hamishwillee - please check all of this back to the excel doc Dugan did for you,  You have many errors in the text.

Use simple pattern matching.

image

Creating a new standard in the naming might be too confusing.
FMUv3, Pihawk3 Debug v3 - have no correlation

Pixhawk Debug Port v3 - make is sound like there is a 3rd version of the debug port, which is true but this it tied to the FMUvN and not a standalone thing.

Pixhawk 1  FMUv2 -  Pixhawk 10 pin ARM Debug
Pixhawk 2  FMUv3 -   6 pin SUR Debug
Pixhawk 3,4   FMUv4, FMUv5  6 pin SH Debug
----- Naming fixed ------
Pixhawk 5X  FMUv5X 10 pin SH Debug
Pixhawk 6 FMUv6   10 pin SH Debug
Pixhawk 6 FMUv6X 10 pin SH Debug

**Comment by hamishwillee** [comment]
@davids5 
Thanks. Re "Creating a new standard in the naming might be too confusing." - absolutely. Wasn't sure right way to approach this - your suggestion is good. 

A couple of confirmations above
- Is the device name for FMUv6x = Pixhawk 6X (ie following the pattern)?
- You also wrote "10 pin SH Debug" but I think you mean 10 pin SUR Debug right?

I also couldn't find other digikey errors other than the one you pointed to (thanks). I did add some links to more keys though. If you see more, please mark them up specifically.

Anyway, all updated as I hope you would want. Please recheck. [Rendered view of this here](https://hamishwillee.gitbooks.io/havdevguide/content/v/swd_2/en/debug/swd_debug.html).

**Comment by davids5** [comment]
> @davids5
> Thanks. Re "Creating a new standard in the naming might be too confusing." - absolutely. Wasn't sure right way to approach this - your suggestion is good.
> 
> A couple of confirmations above
> 
> * Is the device name for FMUv6x = Pixhawk 6X (ie following the pattern)?

Yes my bad FMUv6X  == Pixhawk 6X  
 build names will be lower case i.e.  px4_fmuv5x

> * You also wrote "10 pin SH Debug" but I think you mean 10 pin SUR Debug right?

No - There is in inline question. See https://github.com/PX4/Devguide/pull/984#commitcomment-37940882 - lets wait for confirmations. 

> 
> I also couldn't find other digikey errors other than the one you pointed to (thanks). I did add some links to more keys though. If you see more, please mark them up specifically.
> 
> Anyway, all updated as I hope you would want. Please recheck. [Rendered view of this here](https://hamishwillee.gitbooks.io/havdevguide/content/v/swd_2/en/debug/swd_debug.html).

**Comment by davids5** [comment]
@hamishwillee 

Hamaish Yikes! "You can connect to the debug port using a cable like this one."   

We have a link to the B version of the cable.  

The link needs to be to the A version https://www.digikey.com/products/en?keywords=A06SR06SR30K152A

ALL PX4 cables have a Pin 1 to pin 1 wiring.  So there is a  twist. When laid on a table one connector pin's points UP the other ends pin's down point down, when held with the pin side facing you. Pin1 will be on the same side.

**Comment by davids5** [comment]
@hamishwillee 

> You also wrote "10 pin SH Debug" but I think you mean 10 pin SUR Debug right?

Confirmed "10 pin SH Debug" - please update the docs.  

Vert PN is BM10B-SRSS-TB(LF)(SN)

https://www.digikey.com/product-detail/en/jst-sales-america-inc/BM10B-SRSS-TB-LF-SN/455-1796-2-ND/926702

Side mount PN SM10B-SRSS-TB(LF)(SN)

https://www.digikey.com/product-detail/en/jst-sales-america-inc/SM10B-SRSS-TB-LF-SN/455-1810-2-ND/926716

Cable 
https://www.digikey.com/product-detail/en/jst-sales-america-inc/A10SR10SR30K203A/455-3669-ND/9922219

**Comment by hamishwillee** [comment]
Re https://github.com/PX4/Devguide/pull/984#issuecomment-601700837
(ALL PX4 cables have a Pin 1 to pin 1 wiring ...)I have changed the link to the A version.
[note, I can't see the difference either looking or based on your comment. I guess it doesn't matter as long as people know which number to order]

I also fixed up the links and images to change SUR to SH (10 pin) as you suggested here:
 https://github.com/PX4/Devguide/pull/984#issuecomment-601814082

Please check.

**Review by davids5 — APPROVED** [review]

**Pull request merged**
