### PR TITLE
add astyle documenation

### PR DESCRIPTION
**Pull request by ChristophTobler**
I thought it would make sense to include that. Maybe general code style guidance would also help

### CODE REVIEW

**Review by bkueng — APPROVED** [review]
Looks good to me. @dagar are these versions ok?

**Comment by dagar** [comment]
It's definitely possible to have differences between versions we can't control. Should we limit to the latest version only? I can update CI pretty easily.

**Comment by ChristophTobler** [comment]
Sounds good to me. Should we get rid of https://github.com/PX4/astyle as it doesn't work at the moment and we don't have to maintain it?

**Comment by dagar** [comment]
Yes let's get rid of it. We just need to be able to point Ubuntu users at an acceptable version (packaged).

**Comment by ChristophTobler** [comment]
Do you think source code is not suitable? I can add instructions so that it is straight forward

**Comment by LorenzMeier** [comment]
@ChristophTobler We should try to aim for a packaged version.

**Comment by ChristophTobler** [comment]
Ok. I'll check which one works best

**Comment by ChristophTobler** [comment]
Should we just create our own .deb file with e.g. checkinstall? Because for me only the source installation from https://sourceforge.net/projects/astyle worked. `apt-get install astyle` version produces a huge diff when running `make format`.

**Pull request merged**
