### PR TITLE
Update mavros_offboard.md

### PR DESCRIPTION
**Pull request by ghost**
correct arm_cmd.response.success to arm_cmd.response.mode_sent

### CODE REVIEW

**Review by TSC21 — APPROVED** [review]

**Comment by andre-nguyen** [comment]
Is it just me or do the en and zh versions not match anymore?

**Comment by TSC21** [comment]
They don't in certain details of the text, though the code is right. I didn't update the text for obvious reasons.

**Comment by andre-nguyen** [comment]
The code is different though:

```diff
        if( current_state.mode != "OFFBOARD" &&
            (ros::Time::now() - last_request > ros::Duration(5.0))){
            if( set_mode_client.call(offb_set_mode) &&
-                offb_set_mode.response.mode_sent){
+                offb_set_mode.response.success){
                ROS_INFO("Offboard enabled");
            }
            last_request = ros::Time::now();
        } else {
            if( !current_state.armed &&
                (ros::Time::now() - last_request > ros::Duration(5.0))){
                if( arming_client.call(arm_cmd) &&
-                    arm_cmd.response.success){
+                    arm_cmd.response.mode_sent){
                    ROS_INFO("Vehicle armed");
                }
                last_request = ros::Time::now();
            }
        }
```

**Comment by TSC21** [comment]
Oh gosh you are right. @liang-tang changed the wrong line and I didn't check it properly. Will fix it in a bit.

**Comment by TSC21** [comment]
Fixed here https://github.com/PX4/Devguide/pull/293. Thanks @andre-nguyen!

**Comment by hamishwillee** [comment]
@TSC21 @andre-nguyen  FYI Where possible, we should fix up Chinese content. Not always possible. Ideally translators should be monitoring for changes but you can always ping @FantasyJXF for checks on our Chinese content, or if you make significant changes.

**Comment by TSC21** [comment]
Understood @hamishwillee! I can try it on a new PR (different from #293 though) and ping @FantasyJXF. Can you still merge #293 please?

**Pull request merged**
