### PR TITLE
Flightgear Simulator support documentation

### PR DESCRIPTION
**Pull request by kaklik**
The documentation of FlightGear simulator support from the pull-request: https://github.com/PX4/Firmware/pull/14539

### CODE REVIEW

**Comment by hamishwillee** [comment]
@kaklik Let me know when you're ready for review. On quick scan looks great.

Just a few things I noticed:
1. You will need to add entries to /en/SUMMARY.md to build this.
2. Try keep image sizes low because we don't rescale. The average would probably be 100Kb-200Kb, usually achieved by using Jpg instead of png, and resizing to about 1000px width. Of course the main point is information transfer, so if you need to have higher resolution for detail, feel free. Also I will often have the first "Hero" image bigger to show off what can be done.
3. Please add to this table: http://dev.px4.io/master/en/simulation/#supported-simulators. 
4. I assume does not work with HITL? http://dev.px4.io/master/en/simulation/hitl.html#hardware-in-the-loop-simulation-hitl

**Comment by kaklik** [comment]
@hamishwillee  I resolved the already mentioned notices.  Unfortunately, there happens some evolution in graph handling meantime and the CI fails on unknown `{% endmermaid %}` tag for now.
I do not know how to resolve this failure.

**Comment by hamishwillee** [comment]
@kaklik That's not your fault - the mermaid plugin is breaking lots of stuff so I have removed it and everywhere it is usedI replace it with a dynamically generated image from mermaid js online, and some text showing the original graph (in case we ever need to regenerate it AND mermaid JS is down). 

So replace
```
{% mermaid %}
graph LR;
  FlightGear-->FlightGear-Bridge;
  FlightGear-Bridge-->MAVLink;
  MAVLink-->PX4 SITL;  //NOTE, the space between PX4 and SITL here is invalid
{% endmermaid %}
```
With
```
[![Mermaid Graph ](https://mermaid.ink/img/eyJjb2RlIjoiZ3JhcGggTFI7XG4gIEZsaWdodEdlYXIgLS0-IEZsaWdodEdlYXItQnJpZGdlO1xuICBGbGlnaHRHZWFyLUJyaWRnZSAtLT4gTUFWTGluaztcbiAgTUFWTGluayAtLT4gUFg0X1NJVEw7XG5cdCIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9)](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggTFI7XG4gIEZsaWdodEdlYXIgLS0-IEZsaWdodEdlYXItQnJpZGdlO1xuICBGbGlnaHRHZWFyLUJyaWRnZSAtLT4gTUFWTGluaztcbiAgTUFWTGluayAtLT4gUFg0X1NJVEw7XG5cdCIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9)

<!-- Original mermaid graph
graph LR;
  FlightGear-- >FlightGear-Bridge;
  FlightGear-Bridge-- >MAVLink;
  MAVLink-- >PX4_SITL;
-->
```
The graph looks like this:
[Mermaid Graph](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggTFI7XG4gIEZsaWdodEdlYXIgLS0-IEZsaWdodEdlYXItQnJpZGdlO1xuICBGbGlnaHRHZWFyLUJyaWRnZSAtLT4gTUFWTGluaztcbiAgTUFWTGluayAtLT4gUFg0X1NJVEw7XG5cdCIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9)

Otherwise you're ready for review?

**Comment by kaklik** [comment]
@hamishwillee  I fixed the mermaid diagram.   The pull-request is ready for review.

**Comment by hamishwillee** [comment]
Thanks. I will try reserve some for this tomorrow. If I haven't done this by Monday feel free to ping me.

**Comment by kaklik** [comment]
Hi, @hamishwillee is it possible to merge this pull-request, or there are some improvements required?

**Comment by hamishwillee** [comment]
Thanks @kaklik . This is great thanks. I'll merge and do some minor editorial updates as a post process.

Is this in PX4 CI? Would be great to get early warning when any changes we make might break your build.

**Comment by hamishwillee** [comment]
My further concern is that the multi-vehicle simulation comes off a branch. Can the necessary changes go into PX4 so that they continue to work going forward. Otherwise this simulation will age badly.

**Comment by kaklik** [comment]
The simulator is partially integrated to PX4 CI for now, some work at this topics will be need in a near future.  It is the same for multi-vehicle support branch. The merging of multi-vehicle branch to PX4 master is also planned. I will make another docs pull-request to update this status accordingly. I think it is useful to have a documentation of the current FlightGear simulation capabilities, because it could be instantly used by some individuals.

**Comment by hamishwillee** [comment]
@kaklik I agree, and thanks. Just want to make sure it stays useful :-)

**Pull request merged**
