### PR TITLE
adds calendar link and iframe embed

### PR DESCRIPTION
**Pull request by mrpollo**
the `{% raw %}` code blocks should work to display the iframe correctly according to https://toolchain.gitbook.com/syntax/markdown.html#html

### CODE REVIEW

**Comment by mrpollo** [comment]
screenshot 2017-11-22 10 45 45

**Comment by hamishwillee** [comment]
You can see it rendered [here](https://hamishwillee.gitbooks.io/havdevguide/content/v/6b4a2353427e973c208f3a27a88edf4dd73b508c/en/#calendar--events)

Questions/thoughts:
1. Do we need both calendar link and iframe?
2. iFrames SUCK. Does not scale. 
3. Why the dev guide? Why not user guide? Why not site?
4. IMO this should be below the forums and chat - because as a user the Dronecode calendar is not as important.

**Review by hamishwillee — COMMENTED** [review]
Some questions above

**Comment by hamishwillee** [comment]
@mrpollo There are still open questions for you on this: https://github.com/PX4/Devguide/pull/362#issuecomment-346479812

**Comment by hamishwillee** [comment]
@mrpollo There are still open questions for you on this: #362 (comment)

**Comment by mrpollo** [comment]
@hamishwillee IMO this should be in the docs somewhere + on the site, can you please find a home for the calendar?

**Comment by hamishwillee** [comment]
OK, calendar added to Dronecode site under contribute [here](https://www.dronecode.org/calendar/)

The calendar moved to the [contributing page](https://dev.px4.io/en/contribute/#dev_call) below dev call, and prominently linked from the home page:
image

I'll merge this now. We can make any fixes as a post-process.

**Pull request merged**
