### PR TITLE
Testing custom MAVLink messages

### PR DESCRIPTION
**Pull request by hamishwillee**
@bkueng This adds note about testing custom uorb messages. Suggestion is that you can look in uLog and rebuild QGC and use mavlink inspector. I have not actually done these things, so can you:
- Confirm this is good advice, that you think is clear enough to follow
- Suggest better alternative

I presume best way to test an incoming message  can't really be documented because it will depend on the message. Or could we suggest look at uLog if there is one associated with the incoming message?

### CODE REVIEW

**Comment by hamishwillee** [comment]
@bkueng Slightly unrelated, but example shows how to set up code to stream a message. Is all outgoing traffic handled this way (ie via stream)? What about commands etc - are they sent out as part of a stream or ad-hoc. 
To put it another way, do you think the doc covers all the standard sending scenarios, or just one?

**Comment by bkueng** [comment]
> Confirm this is good advice, that you think is clear enough to follow

I think it's better to not add ulog, as it's another component you need to configure.
It's much simpler to use `uorb top [<message_name>]`, then you see in real-time if your message is published, and even at what rate.

> I presume best way to test an incoming message can't really be documented because it will depend on the message.

Yes, but the most common case is a streamed message. If it is published as a uORB topic, you can also use `uorb top`. Otherwise via printf (and test in SITL first).

> @bkueng Slightly unrelated, but example shows how to set up code to stream a message. Is all outgoing traffic handled this way (ie via stream)? What about commands etc - are they sent out as part of a stream or ad-hoc.
To put it another way, do you think the doc covers all the standard sending scenarios, or just one?

I'd say streaming is the most important and most common one, so I'd leave it with that. Commands need to be acked, so they are not streamed but handled separately. You could explain that if you want to though. For a new command most of it is automatic, since it's already converted into an uORB topic `vehicle_command`.

**Comment by hamishwillee** [comment]
Thanks @bkueng . I've updated with your advice to use `uorb top`. I left in comment about QGC because it might not be obvious if they work end to end that it also needs to be updated with new mavlink library.

Can you check it again please?

**Comment by hamishwillee** [comment]
> I'd say streaming is the most important and most common one, so I'd leave it with that. Commands need to be acked, so they are not streamed but handled separately. You could explain that if you want to though. For a new command most of it is automatic, since it's already converted into an uORB topic vehicle_command.

I would if I "really" understood what needs to be done.

 I'm guessing from what you're saying any new command gets turned into a `vehicle_command` uorb. Presumably any system that wants to handle a particular command listens for that and processes the command. Lots of questions though - what if multiple parts of the system try to handle a command? How is the ack processed/sent by the code that is processing the message? etc etc.

**Comment by hamishwillee** [comment]
... and presumably on that note, we should also have a section on handling new MAV_CMDs in missions.

**Comment by hamishwillee** [comment]
@bkueng I've further added updated to MAVLink 2 as per https://github.com/PX4/Devguide/issues/650

**Review by bkueng — APPROVED** [review]
Ok, let's merge this now and do follow-ups as needed.

**Pull request merged**
