### PR TITLE
Updated dev_env.md

### PR DESCRIPTION
**Pull request by ghost**
Updated dev_env.md in Korean.

### CODE REVIEW

**Comment by jeyong** [comment]
Thanks for joining translation.
It's hard to check PR for each file.
Is it possible to PR after progress of chucks?

**Comment by hamishwillee** [comment]
@jeyong I think we need to move translation to crowdin. Our current approach isn't scalable. The problem is that I am not sure I can import strings, so much of this stuff  might need to be re-imported.  I will do my best to fix that. 

@konjoon Would you like to join the translation team. No particular responsibility, just it will make this sort of change much easier!

**Comment by hamishwillee** [comment]
@jeyong I've sent you a link to the crowdin project as manager - you will be able to accept translations, and invite new people to join the project.

In the meantime, up to you if you wish to accept these translations or not. 

@konjoon I don't know if you have a crowdin account. However we'd welcome your translation. You can see the project here:  https://crwd.in/px4-developer-guide

**Comment by ghost** [comment]
I am a newbie here and of course, I want to join.
By the way, what do you mean by PR?
I cannot understand what you mean at all, jeyong.
I just created the crowdin account but nothing's there with the link.
The only thing I can see is "Project Not Found" with the 404 code.

**Comment by hamishwillee** [comment]
@konjoon Great to hear you want to help. 

Crowdin is a translation tool/service. It basically means that instead of having to look at a whole document at a time you can translate individual strings. This allows you to fix bits of docs, and also see new strings when they are added.

If you go to this link https://crowdin.com/ you will be able to create a login. Once you have done that, the other link should work!

A PR is a pull request. It is a change to code. This place I am writing to you now is a pull request / PR that you created with documentation changes.

**Comment by ghost** [comment]
One more thing to comment. I think the current Korean docs are based on the old English docs so the contents are somewhat different from the current English version.

**Comment by hamishwillee** [comment]
Yes, that is one reason to move to Crowdin. With the current system it is impossible to keep the English and Korean versions synced up. With Crowdin we can.

**Comment by hamishwillee** [comment]
Thank you @konjoon 

We are now using crowdin for managing our translations. This is much better because it always presents the latest strings and so you are not translating old or missing English content.

You will need a [crowdin](https://crowdin.com) login and then you can join the project to translate using https://crowdin.com/project/px4-developer-guide/invite?d=d5j626j6b51733e307p47313e3k4l4

I am therefore closing this PR.

**Pull request closed without merging**
