### PR TITLE
Add airship simulation docs

### PR DESCRIPTION
**Pull request by antonerasm**
Add Gazebo simulation documentation for the new airship vehicle.

Follows on from https://github.com/PX4/Firmware/pull/14862

### CODE REVIEW

**Review by Jaeyoung-Lim — COMMENTED** [review]
@antonerasm Have you tried this on latest master? for me I only see an empty world without the vehicle

**Comment by hamishwillee** [comment]
Same result for me - no airship shown in Gazebo. The docs themselves look good.

**Comment by antonerasm** [comment]
@Jaeyoung-Lim @hamishwillee Yes thanks for pointing it out, I am aware that this is the case on the latest master. I submitted [this PR](https://github.com/PX4/Firmware/pull/15232) to fix the problem as it has to do with the fact that the airship Gazebo SDF model is being auto-generated from a jinja file. Trying to simulate any model described by a jinja file will give the same result. Once that PR is merged, it should be fixed.

**Comment by Jaeyoung-Lim** [comment]
@antonerasm Can you resolve the conflicts on that PR? It is not possible to merge because of the conflicts

**Comment by antonerasm** [comment]
@Jaeyoung-Lim Done : )

**Comment by hamishwillee** [comment]
Also, we need in both this and the user guide and possibly QGC an icon for the airframe reference: http://docs.px4.io/master/en/airframes/airframe_reference.html#airship

**Comment by antonerasm** [comment]
@hamishwillee Thanks for pointing that out. I created and added the svg icon in this PR for the dev guide. I will add it to the user guide and QGC shortly

**Comment by hamishwillee** [comment]
Excellent. Thank you!

**Pull request merged**
