### PR TITLE
Update vscode.md

### PR DESCRIPTION
**Pull request by oneWayOut**
Change Linux 18.04 to Ubuntu 18.04

### CODE REVIEW

**Comment by hamishwillee** [comment]
Thanks very much! Merged. We're having some build issues, so this might not appear live for a little while.

**Comment by oneWayOut** [comment]
Great!
Just one more thing: I wonder why Ubuntu 16.04 allows to build but not debug targets with vscode?
 I have exactly the same problem.

**Comment by hamishwillee** [comment]
> Just one more thing: I wonder why Ubuntu 16.04 allows to build but not debug targets with vscode?
I have exactly the same problem.

No idea. But could not get it to work. More important to get the documentation out that resolve that issue.

**Comment by oneWayOut** [comment]
OK, Thank you!

**Pull request merged**
