### PR TITLE
document out-of-tree modules

### PR DESCRIPTION
**Pull request by bkueng**
...and make sure RPi is called as root.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Gitbook test failed

**Comment by bkueng** [comment]
saw that, but I think it's the gitbook installation. I wouldn't know which of my changes could have caused that.

**Comment by julianoes** [comment]
@bkueng Can you rebase and force push to trigger another build? Or ammend something to the last commit to change the hash.

**Comment by bkueng** [comment]
all good now

**Pull request merged**
