### PR TITLE
SD card layout: change to recommendation to format

### PR DESCRIPTION
**Pull request by hamishwillee**
As discussed in https://github.com/PX4/Devguide/pull/972#discussion_r393535675, Nuttx will format the SD card if mounting fails. However generally safer just to tell them to do this themselves.

### CODE REVIEW

**Comment by bkueng** [comment]
But this now tells everyone to format, even for brand new cards, which is not required.

**Comment by hamishwillee** [comment]
Hmmm. It's a recommendation, not an instruction. But I get your point.

We could change from

> We recommend that you format the SD Card as FAT32 before first use with PX4.

To

> The SD card should be FAT32 formatted for use with PX4. 

or 

> The SD card should be FAT32 formatted for use with PX4. We recommend you reformat cards that are using a different file system.

If not, what do you suggest?

**Comment by bkueng** [comment]
This:
> The SD card should be FAT32 formatted for use with PX4 (which is the default for SD cards). We recommend you reformat cards that are using a different file system.

?

**Comment by hamishwillee** [comment]
sure: https://github.com/PX4/Devguide/commit/6d602fc02989bc23b04a929e53a5108807ddfb54

**Pull request merged**
