### PR TITLE
Adding simulation example for the UUV HippoCampus

### PR DESCRIPTION
**Pull request by NRottmann**
Adding simulation example for the UUV HippoCampus from the Technical University Hamburg-Harburg.

### CODE REVIEW

**Comment by bkueng** [comment]
Thanks!

**Comment by NRottmann** [comment]
You are welcome!

**Comment by hamishwillee** [comment]
@NRottmann  Thanks from me too. Love this vehicle - looks like you're [having a lot of fun](http://px4.io/hippocampus-auv-swarm-px4/)

**Comment by NRottmann** [comment]
Nice :)


Zitat von Hamish Willee <notifications@github.com>:

**Pull request merged**
