### PR TITLE
translate sth

### PR DESCRIPTION
**Pull request by FantasyJXF**
update sth and translate sth

### CODE REVIEW

**Comment by hamishwillee** [comment]
@FantasyJXF Looks good so far. Let me know when enough docs are done to justify pulling this in. Thank you!

**Comment by hamishwillee** [comment]
Your merge is a bit odd - looks like you're adding files to master that we already added. Did you do a rebase?

**Comment by FantasyJXF** [comment]
Eh, I used the `git merge ` not `rebase`

I'm going to fix it today

**Comment by FantasyJXF** [comment]
This PR might contains the #228 PR

**Comment by hamishwillee** [comment]
Looks excellent. You OK for me to merge?

**Comment by FantasyJXF** [comment]
You merge it, I think

**Pull request merged**
