### PR TITLE
small updates, mostly spelling

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by dagar** [comment]
hmm, I used the gitbook editor to make the change and it looks like it altered some white space as well. I'll review/cleanup.

**Comment by dagar** [comment]
Gitbook editor whitespace changes seem to be harmless or for the better.

Please review.

**Comment by LorenzMeier** [comment]
I generally prefer their web editor because the integration is a lot easier.

**Review by bkueng — APPROVED** [review]

**Comment by LorenzMeier** [comment]
Github sync from Gitbook is broken again. It might be worthwhile to try to use the web editor from Gitbook until we figured that one out.

**Comment by dagar** [comment]
I think the only solution is to force the sync one way or the other and then manually restore anything that was lost.

**Pull request merged**
