### PR TITLE
Mention loadable modules in system startup and the app tutorial.

### LINKED ISSUE #656: Add docs for posix dynamic modules on Posix + FIFOs
Support for dynamic modules on Posix (and possibly nuttx, untested) added in https://github.com/PX4/Firmware/pull/10870#issuecomment-439932956

Needs to state what it can be used for and how it is used.
* [ ] Possibly add a section in  [System Startup](http://dev.px4.io/en/concept/system_startup.html) linked from a small note in the [app tutorial](http://dev.px4.io/en/apps/hello_sky.html).

* [x] In addition, the section in [System Startup](http://dev.px4.io/en/concept/system_startup.html) about client/daemon FIFOs is no longer true. 

Hoping that @m-ou-se will create PR :-)

### PR DESCRIPTION
**Pull request by m-ou-se**
Fixes #656

### CODE REVIEW

**Comment by hamishwillee** [comment]
Thanks @m-ou-se . 

You say this only works for Posix builds? 
   - When would you want to declare a (dynamic) module that can only be used on Posix?
   - Can you let me know a few cases where generally the ability to make dynamic modules will improve things?
Basically, I'm trying to understand why/when someone might do this.

Once that is answered I'll merge and do some minor tidy up to fix markdown issues that affect gitbook (but not github) and cross link between the sections.

**Comment by hamishwillee** [comment]
Hi @m-ou-se ,

I'd like to merge this, and I could as-is, but it would be more complete if you could possibly answer https://github.com/PX4/Devguide/pull/663#issuecomment-441487906

If you're not going to be able please let me know.

**Comment by m-ou-se** [comment]
Hey, Sorry for my very late reply.

To answer your questions:

- Most importantly: It makes it easier to make modules written in other languages than C or C++. Getting those to compile together with the rest of PX4 in the same build process would be a lot harder than compiling it as a separate module. For Rust, for example: https://docs.rs/px4/
- It makes it easier to swap optional modules in and out without having to re-compile PX4.
- It also allows for sharing a module for someone to use, without having to share the source code with them (useful for companies producing custom drivers with restrictions, for example).

It could probably be made available on NuttX as well, but it'll cost a lot of memory, as all linker symbols need to be available at run-time, which is not really a problem on Posix platforms.

**Comment by hamishwillee** [comment]
Thanks @m-ou-se - what's 2 months between friends :-). I merged this and added the core info in https://github.com/PX4/Devguide/pull/807 - can you check that is correct/useful? It should be - so this is just a sanity check.

**Pull request merged**
