### PR TITLE
simulation: fix ports (UDP 1456x to TCP 456x)

### PR DESCRIPTION
**Pull request by julianoes**
With the introduction of lockstep the simulation we are now using TCP on a different port.

### CODE REVIEW

**Review by hamishwillee — APPROVED** [review]
Excellent. I'm going to merge. Just FMI this is all in master and going into v1.9.0 right? Or is it in a current stable build?

**Comment by julianoes** [comment]
This is master and going into 1.9.0, yes.

**Comment by ghost** [comment]
Hi , i am not able to launch multiple drones in gazebo and connect it over udp ports. A single drone is getting launched from roslaunch px4 mavros_posix_sitl.launch and i am able to control it from python mavros scripts. But roslaunch px4 multi_uav_mavros_sitl.launch is not able to launch drones. 
roslaunch px4 single_vehicle_spawn.launch is also not working.

please suggest some fix for this. I am stuck on this since past 3 days

**Comment by julianoes** [comment]
@DharnaNar can you create an issue on PX4/Firmware please and add the commands that you have been using, please. Thanks. Then someone can try to reproduce it.

**Pull request merged**
