### PR TITLE
Add aionrobotics r1 rover to instructions

### PR DESCRIPTION
**Pull request by Jaeyoung-Lim**
This PR adds the aion robotics r1 rover model that was added in https://github.com/PX4/Firmware/pull/14652

### CODE REVIEW

**Comment by hamishwillee** [comment]
Thanks @Jaeyoung-Lim 

Can you please shrink the image - 500K still much bigger than necessary.

FYI I also added groupings by vehicle type.

**Comment by hamishwillee** [comment]
PS If generally you push branches to this repo I can edit images too (github allows me to edit text in place here, but not push new images when they are on your repo).

**Comment by Jaeyoung-Lim** [comment]
@hamishwillee Thanks for the changes! I don't have push access to this repo, therefore I was pushing to my fork. I will be happy to push to this repo actually. Saves me a git remote :smiley:

**Comment by hamishwillee** [comment]
@Jaeyoung-Lim I've asked for rights to let you join docs team.

In the meantime, if you squish the image a bit I'll merge this PR.

**Comment by Jaeyoung-Lim** [comment]
@hamishwillee Thanks! Done!

**Comment by hamishwillee** [comment]
Thank you. Wish you hadn't killed my other changes with the force-push. I'll redo.

**Pull request merged**
